blank_issues_enabled: false
contact_links:
  - name: Bugs and Feature Requests
    url: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/new/choose
    about: Do you have a bug or feature request related to the Swift Package Index?
